tap "anomalyco/tap", trusted: { formula: "opencode" }
tap "nikitabobko/tap", trusted: { cask: "aerospace" }

brew "bat"
brew "clang-format"
brew "fzf"
brew "glow"
brew "gnu-tar"
brew "lazygit"
brew "lsd"
brew "media-info"
brew "node"
brew "anomalyco/tap/opencode"
brew "pandoc"
brew "ripgrep"
brew "tmux"
brew "vim"
brew "wget"
brew "yazi"
brew "zoxide"

cask "font-maple-mono-nf-cn"
cask "google-chrome"
cask "karabiner-elements"
cask "kitty"
cask "nikitabobko/tap/aerospace"
cask "raycast"
cask "squirrel-app"
cask "visual-studio-code"
cask "wechat"
