[mgr]
show_hidden = true
show_symlink = false
ratio = [1, 3, 3]

[preview]
wrap = "yes"

[opener]
open = [
	{ run = 'open "$@"', desc = "Open" },
]

[[plugin.prepend_previewers]]
name = "*.tar*"
run  = 'piper --format=url -- tar tf "$1"'

[[plugin.prepend_previewers]]
name = "*.csv"
run  = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
name = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

