[mgr]
show_hidden = true
show_symlink = false
ratio = [1, 3, 3]

[preview]
wrap = "yes"
max_width = 3000
max_height = 3000

[opener]
open = [
	{ run = 'open "$@"', desc = "Open" },
]

[plugin]
prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
]

prepend_previewers = [
  { mime = "{audio,video,image}/*", run = "mediainfo"},
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },

  { name = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
  { name = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
  { name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
]

# For a large file like Adobe Illustrator, Adobe Photoshop, etc
# you may need to increase the memory limit if no image is rendered.
# https://yazi-rs.github.io/docs/configuration/yazi#tasks
[tasks]
  image_alloc      = 1073741824        # = 1024*1024*1024 = 1024MB

# [[plugin.prepend_preloaders]]
# name = "*.docx"
# run  = "office"
#
# [[plugin.prepend_previewers]]
# name = "*.docx"
# run  = "office"
#
# [[plugin.prepend_preloaders]]
# name = "*.pptx"
# run  = "office"
#
# [[plugin.prepend_previewers]]
# name = "*.pptx"
# run  = "office"
#
# [[plugin.prepend_preloaders]]
# name = "*.doc"
# run  = "office"
#
# [[plugin.prepend_previewers]]
# name = "*.doc"
# run  = "office"
