[mgr]
show_hidden = true
show_symlink = false
ratio = [1, 3, 3]

[preview]
wrap = "yes"
max_width = 3000
max_height = 3000

[opener]
open = [
	{ run = 'open "$@"', desc = "Open" },
]

[[plugin.prepend_previewers]]
name = "*.tar*"
run  = 'piper --format=url -- tar tf "$1"'

[[plugin.prepend_previewers]]
name = "*.csv"
run  = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
name = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

# [[plugin.prepend_preloaders]]
# name = "*.docx"
# run  = "office"
#
# [[plugin.prepend_previewers]]
# name = "*.docx"
# run  = "office"
#
# [[plugin.prepend_preloaders]]
# name = "*.pptx"
# run  = "office"
#
# [[plugin.prepend_previewers]]
# name = "*.pptx"
# run  = "office"
#
# [[plugin.prepend_preloaders]]
# name = "*.doc"
# run  = "office"
#
# [[plugin.prepend_previewers]]
# name = "*.doc"
# run  = "office"
