[mgr]
show_hidden = true
show_symlink = false
ratio = [1, 3, 3]

[preview]
wrap = "yes"
max_width = 3000
max_height = 3000

[opener]
drawio = [
	{ run = 'open -a "draw.io" "$@"', desc = "Open with draw.io", for = "macos" },
]

[open]
prepend_rules = [
	{ url = "*.drawio", use = [ "drawio", "reveal" ] },
	{ mime = "text/*",                    use = [ "edit", "open", "reveal" ] },
	{ mime = "application/{json,ndjson}", use = [ "edit", "open", "reveal" ] },
	{ mime = "*/javascript",              use = [ "edit", "open", "reveal" ] },
	{ mime = "inode/empty",               use = [ "edit", "open", "reveal" ] },
]

[plugin]
prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
]

prepend_previewers = [
  { mime = "{audio,video,image}/*", run = "mediainfo"},
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },

  { url = "*.docx", run = 'piper -- pandoc -t markdown "$1" | CLICOLOR_FORCE=1 glow -w=$w -s=dark -' },
  { url = "*.pptx", run = 'piper -- pandoc -t markdown "$1" | CLICOLOR_FORCE=1 glow -w=$w -s=dark -' },
  { url = "*.tar*", run = 'piper -- format=url -- tar tf "$1"' },
  { url = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
]

# For a large file like Adobe Illustrator, Adobe Photoshop, etc
# you may need to increase the memory limit if no image is rendered.
# https://yazi-rs.github.io/docs/configuration/yazi#tasks
[tasks]
  image_alloc      = 1073741824        # = 1024*1024*1024 = 1024MB