#!/usr/bin/env zsh

set -eu

if (( $# != 1 )); then
    print -u2 'Usage: init-server.sh <ssh-host>'
    exit 2
fi

ssh_host=$1
case $ssh_host in
    *[!A-Za-z0-9._-]* | '')
        print -u2 "Invalid SSH host: $ssh_host"
        exit 2
        ;;
esac

repo_url=${DOTFILES_REPO_URL:-https://github.com/Thysrael/dotfiles.git}
remote_port=${REMOTE_PROXY_PORT:-17897}
repo_root=${0:A:h:h}
env_names=()

while IFS= read -r name || [[ -n $name ]]; do
    case $name in
        '' | \#*) continue ;;
        *[!A-Za-z0-9_]* | [0-9]*)
            print -u2 "Invalid environment variable name: $name"
            exit 2
            ;;
    esac

    if (( ! ${+parameters[$name]} )); then
        print -u2 "Environment variable is not set: $name"
        exit 1
    fi
    env_names+=("$name")
done < "$repo_root/scripts/env.list"

source "$repo_root/zsh/proxy.zsh"
pr start "$ssh_host"

proxy_url="http://127.0.0.1:$remote_port"
command ssh "$ssh_host" \
    "DOTFILES_REPO_URL=${(q)repo_url} PROXY_URL=${(q)proxy_url} sh -s" <<'REMOTE'
set -eu

export http_proxy=$PROXY_URL
export https_proxy=$PROXY_URL

dotfiles_dir="$HOME/dotfiles"
if [ -d "$dotfiles_dir/.git" ]; then
    git -C "$dotfiles_dir" pull --ff-only
elif [ -e "$dotfiles_dir" ]; then
    printf 'Error: %s exists and is not a git repository.\n' "$dotfiles_dir" >&2
    exit 1
else
    git clone --depth 1 --recursive --shallow-submodules \
        "$DOTFILES_REPO_URL" "$dotfiles_dir"
fi

git -C "$dotfiles_dir" submodule update --init --recursive --depth 1
make -C "$dotfiles_dir" boot-server
REMOTE

{
    print -r -- '# Generated by init-server.sh.'
    for name in "${env_names[@]}"; do
        printf 'export %s=%q\n' "$name" "${(P)name}"
    done
} | command ssh "$ssh_host" \
    'umask 077; tmp="$HOME/dotfiles/zsh/.custom.zsh.tmp"; cat > "$tmp" && chmod 600 "$tmp" && mv "$tmp" "$HOME/dotfiles/zsh/custom.zsh"'

print "Wrote ${#env_names} environment variables to ~/dotfiles/zsh/custom.zsh."
